// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Employee {
	
	
	public partial class AddEmployee {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox field1;
		
		protected System.Web.UI.WebControls.TextBox field2;
		
		protected System.Web.UI.WebControls.TextBox field3;
		
		protected System.Web.UI.WebControls.TextBox field4;
		
		protected System.Web.UI.WebControls.TextBox field5;
		
		protected System.Web.UI.WebControls.TextBox field6;
		
		protected System.Web.UI.WebControls.DropDownList field7;
		
		protected System.Web.UI.WebControls.Label field8;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.WebControls.Button button2;
	}
}
